[project]
name = "eva"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.4",
    "Cython==3.0.11",
    "gym==0.26.2",
    "open3d==0.17.0",
    "pyopengl==3.1.7",
    "pyzed",
    "requests==2.31.0",
    "tqdm==4.66.2",
    "zerorpc==0.6.3",
    "oculus_reader @ git+https://github.com/rail-berkeley/oculus_reader.git@de73f3d259b3c41c4564f70a64682e24aa3ac31c",
    "hidapi==0.14.0.post4",
    "omegaconf==2.1.2",
    "h5py==3.10.0",
    "imageio==2.34.0",
    "ruff>=0.14.1",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "opencv-python==4.6.0.66",
    "imageio-ffmpeg==0.4.9",
    "opencv-python-headless==4.9.0.80",
    "opencv-contrib-python==4.6.0.66",
    "pandas==1.5.3",
    "openpyxl==3.0.10",
    "parse==1.20.2",
    "patsy==0.5.3",
    "pillow==9.4.0",
    "ply==3.11",
    "protobuf==3.20.1",
    "zict==2.1.0",
    "zope-event==5.0",
]

[tool.uv.sources]
pyzed = { path = "pyzed-4.2-cp310-cp310-linux_x86_64.whl" }

[project.scripts]
eva = "eva:main"

[tool.ruff]
exclude = [
    "external/",
]

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
